# Generated by Django 5.2.14 on 2026-05-19 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_name", models.CharField(max_length=120)),
                ("action", models.CharField(max_length=120)),
                ("entity_type", models.CharField(max_length=60)),
                ("entity_id", models.PositiveIntegerField()),
                ("before_json", models.JSONField(blank=True, null=True)),
                ("after_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("opponent", models.CharField(max_length=120)),
                ("competition", models.CharField(blank=True, max_length=120)),
                ("kick_off", models.TimeField(blank=True, null=True)),
                ("result", models.CharField(blank=True, max_length=40)),
                ("category", models.CharField(blank=True, max_length=30)),
                (
                    "face_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("moon_phase", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("short_name", models.CharField(blank=True, max_length=40)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block", models.CharField(max_length=20)),
                ("row", models.CharField(max_length=20)),
                ("seat_number", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=120, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="SensitiveDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arsenal_membership_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("bank_details", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "transfer_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not Required"),
                            ("pending", "Pending"),
                            ("transferred", "Transferred"),
                            ("listed_on_exchange", "Listed On Exchange"),
                            ("cancelled", "Cancelled"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not Required"),
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_allocations",
                        to="portal.person",
                    ),
                ),
                (
                    "fixture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.fixture"
                    ),
                ),
                (
                    "paid_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_allocations",
                        to="portal.person",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.seat"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fixture", "seat"), name="uniq_fixture_seat"
                    )
                ],
            },
        ),
    ]
